name: sekitarkita_flutter
description: Sekitarkita.id versi Mobile Flutter
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter  
  dio: ^3.0.9
  location: ^3.0.1 
  provider: ^4.0.4
  shared_preferences: ^0.5.6+3
  flutter_local_notifications: ^1.3.0
  ndialog: ^2.0.2+1 
  toast: ^0.1.5
  intl: ^0.16.1
  url_launcher: ^5.4.2
  loading_animations: ^2.1.0 
  flutter_share: ^1.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
 
flutter: 
  uses-material-design: true
  assets:
    - "assets/"
    - "assets/images/"
    - "assets/images/illustration/"